FROM ubuntu:18.04 as build

RUN apt-get update
RUN apt-get install --yes software-properties-common
RUN add-apt-repository --yes ppa:bitcoin/bitcoin
RUN apt-get install --yes libdb5.3++-dev 	
RUN apt-get install --yes libboost-all-dev libzmq3-dev libminiupnpc-dev
RUN apt-get install --yes curl git build-essential libtool autotools-dev
RUN apt-get install --yes automake pkg-config bsdmainutils python3
RUN apt-get install --yes software-properties-common libssl-dev libevent-dev
RUN apt-get install --yes libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
RUN apt-get install --yes libminiupnpc-dev
RUN apt-get install --yes libzmq3-dev
RUN apt-get install --yes libsnappy-dev
RUN apt-get install --yes build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libboost-all-dev libboost-program-options-dev
RUN apt-get install --yes libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev unzip
